// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbCkm_6xrxvKqlek9OqGgFH0rc1thCIgw',
    appId: '1:609180536716:web:0d84678b28315de00f10a9',
    messagingSenderId: '609180536716',
    projectId: 'face-recogination-b46f1',
    authDomain: 'face-recogination-b46f1.firebaseapp.com',
    storageBucket: 'face-recogination-b46f1.firebasestorage.app',
    measurementId: 'G-90K3R4E30H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUDaRPa_U3sW-wyGN7-EH54r8e689FZKg',
    appId: '1:609180536716:android:c2b52572b40feca60f10a9',
    messagingSenderId: '609180536716',
    projectId: 'face-recogination-b46f1',
    storageBucket: 'face-recogination-b46f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgOXIAG7LcfJm8IT6x01JBKat9srnn0GM',
    appId: '1:609180536716:ios:65ad07906d759e2d0f10a9',
    messagingSenderId: '609180536716',
    projectId: 'face-recogination-b46f1',
    storageBucket: 'face-recogination-b46f1.firebasestorage.app',
    iosBundleId: 'com.codewithmurli.faceRecogination',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgOXIAG7LcfJm8IT6x01JBKat9srnn0GM',
    appId: '1:609180536716:ios:65ad07906d759e2d0f10a9',
    messagingSenderId: '609180536716',
    projectId: 'face-recogination-b46f1',
    storageBucket: 'face-recogination-b46f1.firebasestorage.app',
    iosBundleId: 'com.codewithmurli.faceRecogination',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbCkm_6xrxvKqlek9OqGgFH0rc1thCIgw',
    appId: '1:609180536716:web:0ddc144233ec20e80f10a9',
    messagingSenderId: '609180536716',
    projectId: 'face-recogination-b46f1',
    authDomain: 'face-recogination-b46f1.firebaseapp.com',
    storageBucket: 'face-recogination-b46f1.firebasestorage.app',
    measurementId: 'G-PKSGJHTDEJ',
  );
}
